### ISSUE TITLE
Fallback to since boot

### ISSUE THREAD

**Issue by ajaikumarnadar** [asksven/BetterBatteryStats#884] opened 2021-10-14 13:35 UTC
I am getting an error saying "fallback to since boot" and all the stats collected gets deleted automatically to show me.. "no stats have been collected" after 50% battery or so... Don't know what is happening here... I have attached a screenshot for reference.
![Screenshot_2021-10-14-18-59-49-627_com asksven betterbatterystats_xdaedition](https://user-images.githubusercontent.com/31980861/137328094-4f1af3cf-84e4-44a1-9a90-b7460b1af032.jpg)

Bbs 2.6-382
Miui 12.5 based on a11

**Comment by BadCo-NZ** [comment] 2022-01-29 13:19
I am also running into this problem on LineageOS 18.1 on my OnePlus 6t.

**Comment by savvyyyyy** [comment] 2022-03-26 01:39
Same on my XZ2 Compact, Android 11 related maybe ? all permissions for me check as the above screenshot.
@BadCo-NZ did you get a fix for this by any chance ?

**Comment by BadCo-NZ** [comment] 2022-03-26 08:35
> Same on my XZ2 Compact, Android 11 related maybe ? all permissions for me check as the above screenshot. @BadCo-NZ did you get a fix for this by any chance ?

Mine seems to be working now. Not sure if it was fixed my a LineageOS nightly.

![Screenshot_20220326-213352_BBS](https://user-images.githubusercontent.com/50016048/160231626-78559c87-b769-4706-8ca3-332d7e08a53b.png)

**Comment by savvyyyyy** [comment] 2022-03-26 15:51
> > Same on my XZ2 Compact, Android 11 related maybe ? all permissions for me check as the above screenshot. @BadCo-NZ did you get a fix for this by any chance ?
> 
> Mine seems to be working now. Not sure if it was fixed by a LineageOS nightly.

I'm using microG lineageOS 18.1, I'll see if next update fixes it, they don't roll updates nightly. Thanks for getting back to me.

**Comment by BadCo-NZ** [comment] 2022-03-26 21:33
> > > Same on my XZ2 Compact, Android 11 related maybe ? all permissions for me check as the above screenshot. @BadCo-NZ did you get a fix for this by any chance ?
> > 
> > 
> > Mine seems to be working now. Not sure if it was fixed by a LineageOS nightly.
> 
> I'm using microG lineageOS 18.1, I'll see if next update fixes it, they don't roll updates nightly. Thanks for getting back to me.

Indeed, my 'nightlies' are more like weeklies.

Since my original post I did the March 10 update for 18.1

**Comment by asksven** [comment] 2022-06-11 15:45
closed since not reproduced

**Closed by asksven** 2022-06-11 15:45 UTC

**Comment by DARK7BEA5T** [comment] 2024-01-09 19:07
I think I found why.
I can't try it now as I don't have access to a PC currently.
![138747151-76655851-5099-46cc-8849-78ac3a92cac1](https://github.com/asksven/BetterBatteryStats/assets/150522146/69425cb3-1a87-482b-92fa-e2a06e5adde8)
In this pic look, below those command, there are permissions to be granted, grant those with adb too.
Idk if this will work, but it should.

**Comment by DARK7BEA5T** [comment] 2024-01-09 19:21
Anyone found solution?
